# Helm chart values for Production Deployment

# Production mode: disable Django Debug Mode (it can leak passwords/keys)
# Rather than toggling this value, reproduce your problem in the Development
# environment instead.
djangoDebug: false

# Django Secret Key
# This is overridden in eks-production1/prod/mop-values.yaml
djangoSecretKey: "overridden"

# Microlensing Observation Portal Secret Values
# These are overridden in eks-production1/prod/mop-values.yaml
antaresKey: ""
antaresPassword: ""
lcoApiKey: ""
lcoProposalId: ""
lcoUsername: ""

# AWS Credentials
# These are overridden in eks-production1/prod/mop-values.yaml
awsAccessKeyId: ""
awsSecretAccessKey: ""
awsS3Bucket: ""

# Production mode: run two replicas so that we can handle single machine
# outages (whether due to unplanned failure or planned maintenance)
replicaCount: 2

# Production mode: use production PostgreSQL database server
useDockerizedDatabase: false

# Apply database migrations when the application is started
applyDatabaseMigrations: true

# PostgreSQL server configuration is overridden in
# eks-production1/prod/mop-values.yaml
postgresql:
  hostname: "postgres1-cluster.cluster-cple9sjsskrf.us-west-2.rds.amazonaws.com"
  postgresqlDatabase: "mop"
  postgresqlUsername: "mop"
  postgresqlPassword: "overridden"

# MOP Container CPU/Memory Resource Requests/Limits
resources:
  requests:
    cpu: 10m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 1024Mi

# NGINX (static files) CPU/Memory resource Requests/Limits
resources:
  requests:
    cpu: 10m
    memory: 16Mi
  limits:
    cpu: 1000m
    memory: 512Mi

# HTTP router configuration
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx-ingress-public
    # Turn these on to disable all request buffering. In that case, you are on
    # your own in case of a DoS (Denial of Service) attack, or broken clients, or ..
    #nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
    #nginx.ingress.kubernetes.io/proxy-body-size: "0"
  hosts:
    - host: mop.lco.global
      paths:
        - "/"

# CronJob: Fit Alive Events
fitaliveevents:
  enabled: true
  resources:
    requests:
      cpu: 10m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1024Mi

# CronJob: Fit Need Events
fitneedevents:
  enabled: true
  resources:
    requests:
      cpu: 10m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1024Mi
# CronJob: Run TAP
runtap:
  enabled: true
  resources:
    requests:
      cpu: 10m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1024Mi

# CronJob: Harvest IPAC ZTF
harvestztfipac:
  enabled: true
  resources:
    requests:
      cpu: 10m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1024Mi

# CronJob: Harvest GAIA
harvestgaia:
  enabled: true
  resources:
    requests:
      cpu: 10m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1024Mi
      
# CronJob: Harvest MOA
harvestmoa:
  enabled: true
  resources:
    requests:
      cpu: 10m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1024Mi

# CronJob: Add Galactic Coordinates
addgalacticcoordinates:
  enabled: true
  resources:
    requests:
      cpu: 10m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1024Mi
      
# CronJob: Open targets to OMEGA users
opentargetstoomegausers:
  enabled: true
  resources:
    requests:
      cpu: 10m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1024Mi    
