apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "mop.fullname" . }}-fitaliveevents
  labels:
    app.kubernetes.io/name: {{ include "mop.name" . }}
    helm.sh/chart: {{ include "mop.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: "fitaliveevents"
spec:
  schedule: "* */4 * * *"
  concurrencyPolicy: "Forbid"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: mopfitaliveevents        
              image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command: 
                - python
                - manage.py
                - fit_all_events_PSPL
                - alive
              env:
                {{ include "mop.extraEnv" . | nindent 12 }}
                {{ include "mop.backendEnv" . | nindent 12 }}
                - name: "ANTARES_KEY"
                  valueFrom:
                  secretKeyRef:
                       name: mop
                       key: ANTARES_KEY
                - name: "ANTARES_PWD"
                  valueFrom:
                  secretKeyRef:
                       name: mop
                       key: ANTARES_PWD
                - name: "SECRET_KEY"
                  valueFrom:
                  secretKeyRef:
                       name: mop
                       key: SECRET_KEY
                - name: "LCO_API_KEY"
                  valueFrom:
                  secretKeyRef:
                       name: mop
                       key: LCO_API_KEY
                - name: "LCO_PROPOSAL_ID"
                  valueFrom:
                  secretKeyRef:
                       name: mop
                       key: LCO_PROPOSAL_ID

                - name: "LCO_USERNAME"
                  valueFrom:
                  secretKeyRef:
                       name: mop
                       key: LCO_USERNAME
          restartPolicy: Never


